---
- name: Dotfiles - Ensure Git is installed
  package:
    name: git
    state: present

- name: Dotfiles - Check if directory exists
  stat:
    path: "~/.dotfiles/"
  register: repo_directory

- name: Dotfiles - Clone repository and copy to home directory
  shell: |
    git clone --separate-git-dir=$HOME/.dotfiles https://github.com/BaDxKaRMa/.dotfiles.git /tmp/tmpdotfiles &&
    rsync --recursive --verbose --exclude '.git' /tmp/tmpdotfiles/ $HOME/ &&
    rm -r /tmp/tmpdotfiles
  become: yes
  become_user: "{{ ansible_user_id }}"
  when: not repo_directory.stat.exists

- name: Dotfiles - Disable showing untracked files
  command: "git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no"
  become: yes
  become_user: "{{ ansible_user_id }}"
