---
- name: Install CTF tools on Ubuntu
  become: yes
  apt:
    name:
      - gobuster
      - nikto
      - hashcat
  when: ansible_distribution == "Ubuntu"

- name: Install CTF tools on MacOSX
  community.general.homebrew:
    name:
      - gobuster
      - nikto
      - hashcat
  when: ansible_distribution == "MacOSX"
