---
- name: Install neovim on Ubuntu
  become: true
  apt:
    name:
      - neovim
  when: ansible_distribution == "Ubuntu"

- name: Install neovim on MacOX
  community.general.homebrew:
    name:
      - neovim
  when: ansible_distribution == "MacOSX"
