---
- name: Define packages
  set_fact:
    packages:
      - ack
      - asciinema
      - awscli
      - bat
      - cmatrix
      - coreutils
      - docker
      - docker-compose
      - dos2unix
      - exiftool
      - fortune
      - fzf
      - gh
      - gifsicle
      - git
      - gnupg
      - grepcidr
      - hcxtools
      - htop
      - imagemagick
      - jq
      - llvm
      - lolcat
      - lsd
      - luarocks
      - mtr
      - neofetch
      - nmap
      - openvpn
      - p7zip
      - pipx
      - pwgen
      - ripgrep
      - ruby
      - samba
      - socat
      - speedtest-cli
      - telnet
      - tldr
      - tmux
      - tree
      - vim
      - virtualenv
      - wget
      - wireshark
      - yarn
    mac_only:
      - diff-so-fancy
      - docker-machine
      - fd
      - glow
      - lua-language-server
      - pfetch
      - poetry
      - prettier
      - pyenv
      - pyright
      - readline
      - rust
      - snyk/tap/snyk
      - sqlite
      - stylua
      - terminal-notifier
      - the_silver_searcher
      - xz
      - z
      - zlib
      - 1password-cli
      - badxkarma/badxkarma/pokemonsay
      - pinentry-mac
      - fsouza/prettierd/prettierd
      - 1password
      - iterm2
      - font-monaspace-nerd-font
      - postman
      - copyq
      - keka
      - obsidian
      - shottr
      - font-hack-nerd-font
      - font-monaspace-nerd-font
      - maccy

- name: Install packages on apt based systems
  become: true
  apt:
    name: "{{ item }}"
  loop: "{{ packages }}"
  when: ansible_distribution in ['Ubuntu', 'Debian', 'Kali']

- name: Install packages on MacOSX
  community.general.homebrew:
    name: "{{ item }}"
  loop: "{{ packages + mac_only }}"
  when: ansible_distribution == 'MacOSX'
