---
- name: Install nvim in Linux
  import_tasks: linux.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Fedora"

- name: Install nvim in macOS
  import_tasks: macos.yml
  when: ansible_distribution == "MacOSX"
